-- Generated by tools/update-fonts.sh - lists the fonts bundled in the Fonts folder.
local _, ns = ...
ns.bundledFonts = {
    "Anton-Regular.ttf",
    "Bangers-Regular.ttf",
    "BebasNeue-Regular.ttf",
    "BlackOpsOne-Regular.ttf",
    "BowlbyOne-Regular.ttf",
    "LilitaOne-Regular.ttf",
    "LuckiestGuy-Regular.ttf",
    "PassionOne-Black.ttf",
    "RussoOne-Regular.ttf",
    "TitanOne-Regular.ttf",
}
