#!/bin/sh
# Writes BetterDamageText/FontList.lua listing every .ttf in BetterDamageText/Fonts,
# so bundled fonts show up in the settings window's font list.
# Run it after adding or removing fonts (the release workflow runs it too).
cd "$(dirname "$0")/../BetterDamageText" || exit 1
{
    echo "-- Generated by tools/update-fonts.sh - lists the fonts bundled in the Fonts folder."
    echo "local _, ns = ..."
    echo "ns.bundledFonts = {"
    for f in Fonts/*.ttf Fonts/*.TTF; do
        [ -e "$f" ] && echo "    \"$(basename "$f")\","
    done
    echo "}"
} > FontList.lua
cat FontList.lua
